### ISSUE TITLE
Clicking on the “Manage all masks” link in the Field Icon menu makes the add-on think the user has logged out of their Relay account

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay-add-on#314]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have at least one alias created;
- Have the latest Stage version of the add-on installed;
- Have the Relay Field Icon displayed;

#### Steps to reproduce:
1. Go to any site that displays a fill-able email field;
2. Click on the Relay Field Icon;
3. Click on the “Manage all masks” link;
4. Open the Add-on toolbar menu and observe it;
5. Go back to the fill-able email field;
6. Click on the Relay Field Icon and observe its menu;

#### Expected result:
- The menus of the Add-on should be displayed correctly to the logged-in user;

#### Actual result:
- After clicking the “Manage all masks” link, the Add-on menus look like the user is logged off;

#### Notes:
- There is a brief moment after clicking the “Manage all masks” link where the Relay Homepage is visible, and on it there is no user logged in;
- This problem can be fixed by refreshing the Relay dashboard or by clicking on the “Continue” button inside the “not-signed-in” view of the Add-on toolbar menu;
- See attached media:
![logout](https://user-images.githubusercontent.com/85748693/163585834-6376220d-54a3-4c21-a5c9-63d3c6f231f7.gif)

**Comment by Vinnl** [comment]
The brief moment of showing the Relay homepage was fixed by https://github.com/mozilla/fx-private-relay/pull/1816. I'm not sure if that fixes the other issue though.

**Comment by maxxcrawford** [comment]
@Vinnl I am still able to reproduce it. I have a PR (#327) that addresses this issue further, but still doesn't solve the root issue. My PR can be adjusted along with the website for a full fix. I'll sync with you directly.
